### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by DavidOhanyan**
while_loop and history file

### CODE REVIEW

**Review by KarenDanielyan — CHANGES_REQUESTED** [review]
1. Why do you include `minishell.h` in `minishell.h`???
2. Do not put the history file in the src folder. Src is only for source files. Put it in either the Assets folder or move it to ~.
3. Rename the .history file to .minishell_history, as there are other shells in your PC and their naming convention is like this: `.<shell-name>_history`.
4. argc -> ac, argv->av.

**Review by KarenDanielyan — CHANGES_REQUESTED** [review]
Additionally, bring the strcmp("42") back as otherwise we can't exit the application.

**Comment by DavidOhanyan** [comment]
Done.

**Review by KarenDanielyan — APPROVED** [review]
Great Success

**Pull request merged**
